#!/bin/sh

dot_list=(
  bashrc \
  emacs \
  gitconfig \
  gitignore \
  jnewsrc \
  mozilla \
  msmtprc \
  muttrc \
  signature \
  slrnrc \
  ssh \
  thunderbird \
  vim \
  vimrc \
  Xdefaults \
  clang-format \
  wallpaper.jpg \
  xinitrc \
  zshrc \
  fehbg \
)

for f in ${dot_list[@]}; do
  ln -s "$AFS_DIR/.confs/$f" "$HOME/.$f"
done

ln -s "$AFS_DIR/dotfiles_epita/install.sh" "$HOME/install.sh"
ln -s "$AFS_DIR/dotfiles_epita/packages.txt" "$HOME/packages.txt"
ln -s "$AFS_DIR/dotfiles_epita/config" "$HOME/.config"
ln -s "$AFS_DIR/dotfiles_epita/wallpaper.png" "$HOME/wallpaper.png"
